# Generated by Django 3.1.1 on 2020-09-02 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NSR', models.CharField(max_length=9, verbose_name='NSR')),
                ('type', models.IntegerField(verbose_name='type')),
                ('date', models.DateField(verbose_name='date')),
                ('hour', models.DateTimeField(verbose_name='hour')),
                ('PIS', models.CharField(max_length=12, verbose_name='PIS')),
            ],
        ),
    ]
