# Generated by Django 3.1.1 on 2020-09-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAFD', '0002_company_employees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='celPhone',
            field=models.CharField(max_length=11, verbose_name='celPhone'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='celPhone',
            field=models.CharField(max_length=11, verbose_name='celPhone'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='phone'),
        ),
    ]
