# Generated by Django 3.1.1 on 2020-09-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppAFD', '0003_auto_20200902_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='hour',
            field=models.TimeField(verbose_name='hour'),
        ),
    ]
