# Generated by Django 3.1.1 on 2020-09-03 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAFD', '0004_auto_20200902_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='NSR',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='type',
        ),
    ]
